[build]
command = 'nuxi build'
environment = {NODE_VERSION = '20', SERVER_PRESET='netlify_edge'}
publish = 'dist'

[dev]
  framework = "nuxt"
  command= "nuxi dev"
  environment = {SERVER_PRESET='netlify_edge'}
  autoLaunch = false
  targetPort = 3000