[build]
command = 'nuxi prepare && nuxi build --dotenv .env.production'
environment = {NODE_VERSION = '20', SERVER_PRESET='netlify-edge'}
publish = 'dist'
framework = "nuxt"

[dev]
  framework = "nuxt"
  command= "nuxi dev --dotenv .env.local"
  environment = {SERVER_PRESET='netlify_edge'}
  autoLaunch = false
  targetPort = 3000

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  # optional, deploy the lighthouse report to a path under your site
  # [plugins.inputs.audits]
  #   output_path = "reports/lighthouse.html"
