[context.production]
command = 'nuxi prepare && nuxi build'
publish = '/dist'
framework = "nuxt"
autoLaunch = false

[context.production.environment]
#  ESLINT_USE_FLAT_CONFIG = true
  NODE_VERSION = '20'
  SERVER_PRESET='netlify_edge'
#  LIST_BOOK_URL='https://gist.githubusercontent.com/hamar030/3ed4a54ec9f2e8e1721627714193fdcc/raw/list_book.yaml'
  
[[context.production.plugins]]
  package = "@netlify/plugin-lighthouse"
  # optional, deploy the lighthouse report to a path under your site
  # [plugins.inputs.audits]
  #   output_path = "reports/lighthouse.html"

[dev]
  framework = "nuxt"
  command= "nuxi dev"
  autoLaunch = false
  targetPort = 3000

[context.dev.environment]
#  ESLINT_USE_FLAT_CONFIG = true
  NODE_VERSION = '20'
  SERVER_PRESET= 'netlify_edge'
  LIST_BOOK_URL= '/data/list_book_local.yaml'

# The following redirect is intended for use with most SPAs that handle
# routing internally.
# [[redirects]]
#     from = "/*"
#     to = "/index.html"
#     status = 200

# [[headers]]
#     # Define which paths this specific [[headers]] block will cover.
#     for = "/*"
#         [headers.values]
#         Access-Control-Allow-Origin = "*"
