[[redirects]]
force = true
from = '/api/*'
status = 200
to = '/.netlify/functions/:splat'

[[redirects]]
from = '/*'
status = 200
to = '/index.html'

[build]
command = 'vue-tsc && vite build'
environment = {NODE_VERSION = '20'}
publish = 'dist'

[dev]
  framework = "vite"
  autoLaunch = false
  targetPort = 5173